DDOKDDOK/views/test_room_views.py
import base64
from datetime import datetime
from flask import Blueprint, render_template, request, g, url_for, jsonify
from werkzeug.utils import redirect
import secrets

from DDOKDDOK.models import Professor, TestRoom, Student, Log
from DDOKDDOK import db
from DDOKDDOK.views import auth_views

bp = Blueprint('test_room', __name__, url_prefix='/test_room')

""" 전역 변수 """
program_list = ["크롬", "마이크로소프트 엣지", "파이어폭스", "사파리", "카카오톡", "메모장", "계산기"]
no_screen_image = open('./static/img/no_screen.png', 'rb').read()
global_images = dict()  # 전체 화면 공유 이미지 저장 딕셔너리 (test_room_id로 구분)
watching_log_buffer = dict()   # watching 페이지 부정행위 실시간 로그 딕셔너리 (test_room_id로 구분)
# watching_detail 페이지 부정행위 실시간 로그 딕셔너리 (test_room_id/student_id로 구분)
watching_detail_log_buffer = dict()


@bp.route('/', methods=["GET"])
@bp.route('/menu', methods=["GET"])
@auth_views.login_required
def menu():
    return render_template('test_room/menu.html')


@bp.route('/make', methods=["GET"])
@auth_views.login_required
def make():
    """ 시험 생성 """
    test_room_id = secrets.token_urlsafe(11)
    return render_template('test_room/make.html', test_room_id=test_room_id, program_list=program_list)


@bp.route('/make_ajax', methods=['GET', 'POST'])
def make_ajax():
    """ 시험 생성 정보 받기 & 데이터베이스 변경 """
    test_room_id = request.form['test_room_id']
    professor_id = request.form['professor_id']
    block_list = request.form['block_list']
    date = request.form['date'].split('-')
    start = request.form['start_time'].split(':')
    end = request.form['end_time'].split(':')
    start_date = datetime(int(date[0]), int(date[1]), int(
        date[2]), int(start[0]), int(start[1]))
    end_date = datetime(int(date[0]), int(date[1]), int(
        date[2]), int(end[0]), int(end[1]))
    title = request.form['title']

    # TestRoom 객체 생성
    test_room = TestRoom(
        id=test_room_id,
        professor=Professor.query.get(professor_id),
        block_list=block_list,
        start_date=start_date, end_date=end_date, title=title, state="before")
    db.session.add(test_room)

    # Student 객체 생성
    length = request.form['length']
    for i in range(int(length)):
        img = request.files[str(i)]
        student_id = img.filename[:8]
        image_data = img.read()
        student = Student(
            id=student_id, test_room_id=test_room_id, image=image_data)
        db.session.add(student)
    db.session.commit()
    return "Make Ajax Success"


@bp.route('/edit_list', methods=["GET"])
@auth_views.login_required
def edit_list():
    """ 수정 가능한 시험 리스트 """
    professor = Professor.query.get(g.user.id)
    test_room_list = []
    for t in professor.test_room_set:
        test_room_list.append((t.id, t.state, t.title, str(
            t.start_date)[:16], str(t.end_date)[10:16]))
    return render_template('test_room/edit_list.html', test_room_list=test_room_list)


@bp.route('/edit/<string:test_room_id>', methods=["GET"])
@auth_views.login_required
def edit(test_room_id):
    """ 시험 수정 """
    # 데이터베이스에서 시험 정보 로드
    test_room = TestRoom.query.get(test_room_id)
    title = test_room.title
    block_list = test_room.block_list.split(';')[:-1]
    start_date = str(test_room.start_date)
    end_date = str(test_room.end_date)
    date = start_date[0:10]
    start_time = start_date[11:16]
    end_time = end_date[11:16]
    student_list = []
    image_list = []
    for s in test_room.student_set:
        student_list.append(s.id)
        # python의 bytes를 javascript에서 그대로 못 읽어와서... base64 변환 적용
        img = base64.b64encode(s.image).decode()
        image_list.append(img)
    block_list_ = []
    for i in range(len(program_list)):
        if program_list[i] in block_list:
            block_list_.append(i)
    return render_template('test_room/edit.html', test_room_id=test_room_id, title=title, program_list=program_list, date=date, start_time=start_time,
                           end_time=end_time, block_list=block_list, block_list_=block_list_, student_list=student_list, image_list=image_list)


@bp.route('/edit_ajax', methods=['GET', 'POST'])
def edit_ajax():
    """ 시험 수정 정보 받기 & 데이터베이스 변경 """
    test_room_id = request.form['test_room_id']
    block_list = request.form['block_list']
    title = request.form['title']
    date = request.form['date'].split('-')
    start = request.form['start_time'].split(':')
    end = request.form['end_time'].split(':')
    start_date = datetime(int(date[0]), int(date[1]), int(
        date[2]), int(start[0]), int(start[1]))
    end_date = datetime(int(date[0]), int(date[1]), int(
        date[2]), int(end[0]), int(end[1]))

    # TestRoom 객체 삭제 후 다시 생성
    professor_id = TestRoom.query.get(test_room_id).professor_id
    test_room = TestRoom.query.get(test_room_id)
    db.session.delete(test_room)
    db.session.commit()
    test_room = TestRoom(
        id=test_room_id,
        professor=Professor.query.get(professor_id),
        block_list=block_list,
        start_date=start_date, end_date=end_date, title=title, state="before")
    db.session.add(test_room)

    # Student 객체 생성
    length = request.form['length']
    for i in range(int(length)):
        img = request.files[str(i)]
        student_id = img.filename[:8]
        image_data = img.read()
        student = Student(
            id=student_id, test_room_id=test_room_id, image=image_data)
        db.session.add(student)
    db.session.commit()
    return "Edit Ajax Success"


@bp.route('/delete/<string:test_room_id>', methods=["GET"])
def delete(test_room_id):
    """ 시험 삭제 """
    test_room = TestRoom.query.get(test_room_id)
    db.session.delete(test_room)
    db.session.commit()
    return redirect(url_for('test_room.edit_list'))


@bp.route('/watching_list', methods=["GET"])
@auth_views.login_required
def watching_list():
    """ 입장 가능 시험 리스트 """
    professor = Professor.query.get(g.user.id)
    test_room_list = []
    for t in professor.test_room_set:
        test_room_list.append((t.id, t.state, t.title, str(
            t.start_date)[:16], str(t.end_date)[10:16]))
    return render_template('test_room/watching_list.html', test_room_list=test_room_list)


@bp.route('/watching_before/<string:test_room_id>', methods=["GET"])
@auth_views.login_required
def watching_before(test_room_id):
    """ 시험 시작 전 화면  """
    test_room = TestRoom.query.get(test_room_id)
    student_list = []
    for s in test_room.student_set:
        student_list.append(s.id)
    return render_template('test_room/watching_before.html', test_room_id=test_room_id, title=test_room.title, start_date=str(test_room.start_date)[:16], end_date=str(test_room.end_date)[10:16], student_list=student_list)


@bp.route('/start/<string:test_room_id>', methods=["GET"])
@auth_views.login_required
def start(test_room_id):
    """ 시험 시작 """
    # 화면 공유 이미지 딕셔너리 생성
    test_room = TestRoom.query.get(test_room_id)
    images = dict()
    log_buffer = dict()
    for s in test_room.student_set:
        images[s.id] = no_screen_image
        log_buffer[s.id] = list()
    global_images[test_room_id] = images

    # 부정행위 로그 버퍼 생성
    watching_log_buffer[test_room_id] = set()
    # 학생 세부정보 페이지 부정행위 로그 버퍼 생성
    watching_detail_log_buffer[test_room_id] = log_buffer

    # state를 watching으로 변경
    test_room = TestRoom.query.get(test_room_id)
    test_room.state = "watching"
    db.session.add(test_room)
    db.session.commit()

    print(f"========== {test_room_id}번 시험 시작")
    return redirect(url_for('test_room.watching', test_room_id=test_room_id))


@bp.route('share_screen/<string:test_room_id>/<int:student_id>', methods=['POST'])
def share_screen(test_room_id, student_id):
    """ HTTP로 화면 받기 """
    test_room = TestRoom.query.get(test_room_id)
    state = test_room.state
    # 화면 이미지 저장
    if state == "watching":
        image = base64.b64decode(request.form["image"])
        global_images[test_room_id][student_id] = image

    # 시험 상태 보내기
    json = dict()
    json["state"] = state
    return jsonify(json)


""" 제거 필요 """
# def gen_frames(test_room_id, student_id):
#     while True:
#         test_room = TestRoom.query.get(test_room_id)
#         state = test_room.state
#         # 화면 이미지 저장
#         if state == "watching":
#             image = global_images[test_room_id][student_id] # 왜 에러??
#         else:
#             image = no_screen_image
#         frame = bytearray(image)
#         yield (b'--frame\r\n'
#                b'Content-Type: image/png\r\n\r\n' + frame + b'\r\n')
#
#
# @bp.route('/screen_socket_feed/<string:test_room_id>/<int:student_id>')
# @auth_views.login_required
# def screen_socket_feed(test_room_id, student_id):
#     return Response(gen_frames(test_room_id, student_id), mimetype='multipart/x-mixed-replace; boundary=frame')
""" 제거 필요 """


@bp.route('/watching/<string:test_room_id>', methods=["GET"])
@auth_views.login_required
def watching(test_room_id):
    """ 시험 중 화면 """
    test_room = TestRoom.query.get(test_room_id)
    student_list = []
    for s in test_room.student_set:
        student_list.append(s.id)
    return render_template('test_room/watching.html', test_room_id=test_room_id, title=test_room.title,
                           start_date=str(test_room.start_date)[
                               :16], end_date=str(test_room.end_date)[10:16],
                           student_list=student_list)


@bp.route('/student_login/<string:test_room_id>/<int:student_id>', methods=['POST'])
def student_login(test_room_id, student_id):
    """ 학생 로그인 (학생 이미지, 시험 시작, 종료, 차단 프로그램 전송) """
    print("========== 학생 로그인", test_room_id, student_id)
    json = dict()
    test_room = TestRoom.query.get(test_room_id)
    if test_room is not None:
        json["test_room"] = "yes"
        student = Student.query.filter(
            Student.id == student_id, Student.test_room_id == test_room_id).first()
        if student is not None:
            json["student"] = "yes"
            # 학생 이미지 전송
            json["student_image"] = base64.b64encode(student.image).decode()
            # 시험 제목 전송

DDOKDDOK/templates/test_room/edit.html
{% extends 'base.html' %}
{% block content %}

<div class="area__edit area__global">
    <h2 class="text-center pt-2"><strong>시험 수정</strong></h2>
    <h4 class="text-center border-bottom pb-3">시험 번호 : {{ test_room_id }}</h4>

    <div class="container container1 my-3 mx-4 float-left">
        <h3 class="text-center border-bottom py-2">시험 제목 입력</h3>
        <div class="form-group">
            <input type="text" class="form-control" name="title" id="title" value="{{ title }}">
        </div>
        <h3 class="text-center border-bottom py-2 mt-2">시험 시간 설정</h3>
        <form>
            <div><input type="date" id="dateForm" value='{{ date }}'></div>
            <div class="mt-2">
                <input type="time" id="starttimeForm" value='{{ start_time }}'>
                ~
                <input type="time" id="endtimeForm" value='{{ end_time }}'>
            </div>
        </form>
    </div>

    <div class="container container2 my-3 mx-4 float-left">
        <h3 class="text-center border-bottom py-2">차단 프로그램 선택</h3>
        <ul class="list-group">
            {% for program in program_list %}
                <li class="list-group-item mb-2">
                    <div class="form-checkbox ml-3">
                        <input class="form-check-input" type="checkbox" value="" id="checkbox-input{{ loop.index - 1 }}">
                        <label class="form-check-label" for="checkbox{{ loop.index - 1 }}" id="checkbox-label{{ loop.index - 1 }}">{{ program }}</label>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>

    <div class="container container3 my-3 mx-4 float-left">
        <h3 class="text-center border-bottom py-2">학생 등록</h3>
        <form enctype="multipart/form-data">
            <ul class="list-group mb-3">
                <li class="list-group-item">1. 학생 사진을 등록하십시오.</li>
                <li class="list-group-item">2. 파일 이름을 학번으로 설정하십시오.</li>
            </ul>
            <div class="custom-file">
                <input type="file" class="custom-file-input" id="input_images" name="images[]" multiple>
                <label class="custom-file-label" data-browse="Browse">예) 20170843.jpg</label>
            </div>
        </form>
        <h3 class="text-center border-bottom py-2 mt-4">등록한 학생 리스트</h3>
        <div id="image_list"></div>
    </div>
</div>

<div class="button-edit">
    <a href="{{ url_for('test_room.delete', test_room_id=test_room_id) }}" class="btn btn-danger btn-lg m-1"><strong>시험 삭제</strong></a>
    <button class="btn btn-success btn-lg" id="editTestRoomBtn"><strong>시험 수정</strong></button>
</div>


<script>
    // 시작 시간 변경 시 종료 시간 자동 변경 (+1시간)
    $('#starttimeForm').change(() => {
        startTime = $('#starttimeForm').val();
        h = Number(startTime.slice(0, 2)) + 1;
        if (h < 10) {
            h = '0' + h;
        }
        m = startTime.slice(3, 5);
        $('#endtimeForm').attr({'value': h + ':' + m});
    });

    // 학생 리스트에 추가
    let image_list = [];
    const input_images = document.getElementById("input_images");
    input_images.addEventListener("change", uploadImages, false);
    function uploadImages(images = null) {
        if (images.type == "change") {
            images = this.files;
        }
        let bufferLen = image_list.length;
        for (let i = 0; i < images.length; i++) {
            let image = images[i];
            console.log(image);
            image_list.push(image);
            let div1 = document.createElement("div");
            div1.className = "card mt-1 mb-1";
            div1.style.width = "100%";
            let div2 = document.createElement("div");
            div2.className = "row no-gutters";

            let img = document.createElement("img");
            img.src = URL.createObjectURL(image);
            img.style = "max-width:100px; max-height: 130px;";
            div2.appendChild(img);

            let div3 = document.createElement("div");
            div3.className = "card-body";

            let span = document.createElement("span");
            span.className = "card-text";
            span.style = "white-space: pre-line;";
            span.innerText = image.name;
            div3.appendChild(span);

            let button = document.createElement("button");
            button.className = "btn btn-primary float-right deleteImgBtn" + (i + bufferLen);
            button.innerText = "삭제";
            button.addEventListener("click", deleteImage);
            div3.appendChild(button);

            div2.appendChild(div3);
            div1.appendChild(div2);
            document.getElementById("image_list").appendChild(div1);
        }
    }

    // 학생 리스트에서 삭제
    function deleteImage() {
        let index = $(this).parent().parent().parent().index();
        image_list.splice(index,1);
        this.parentNode.parentNode.parentNode.parentNode.removeChild(this.parentNode.parentNode.parentNode);
    }

    // 이미지 url을 파일 형태로 변환
    const dataURLtoFile = (dataurl, fileName) => {
        var arr = dataurl.split(','),
            mime = arr[0].match(/:(.*?);/)[1],
            bstr = atob(arr[1]), 
            n = bstr.length, 
            u8arr = new Uint8Array(n);
            
        while(n--){
            u8arr[n] = bstr.charCodeAt(n);
        }
        return new File([u8arr], fileName, {type:mime});
    }

    // 기존 데이터 로딩
    $(document).ready(() => {
        // 프로그램 차단 리스트 로딩
        '{% for b in block_list_ %}'
            $('#checkbox-input' + '{{ b }}').prop('checked',true);
        '{% endfor %}'

        // 학생 리스트 로딩
        let images = [];
        '{% for img in image_list %}'
            console.log('{{ student_list[loop.index - 1] }}');
            image = "data:image/jpeg;base64," + '{{ img }}';
            file = dataURLtoFile(image, '{{ student_list[loop.index - 1] }}' + ".jpg");
            console.log(file);
            images.push(file);
        '{% endfor %}'
        uploadImages(images);
    });

    // 시험 수정 버튼 클릭 시 서버로 데이터 전송
    $('#editTestRoomBtn').click( () => {   

        // 차단 프로그램 리스트 받아오기 (CheckBox)
        let block_list_string = "";
        for (let i = 0; i < '{{ program_list|length }}'; i++) {
            text = $('#checkbox-label' + i).text();
            if($('#checkbox-input' + i).is(":checked") === true) {
                block_list_string += text + ";";
            }
        }

        // 전송 할 폼데이터 생성
        let formdata = new FormData();
        formdata.append('test_room_id', '{{ test_room_id }}');
        formdata.append('professor_id', '{{ g.user.id }}');
        formdata.append('title', $('#title').val());
        formdata.append('block_list', block_list_string);
        formdata.append('date', document.getElementById('dateForm').value);
        formdata.append('start_time', document.getElementById('starttimeForm').value);
        formdata.append('end_time', document.getElementById('endtimeForm').value);
        formdata.append('length', image_list.length);
        for (let i = 0; i < image_list.length; i++) {
            formdata.append(i, image_list[i]);
        }
         
        // ajax 전송
        $.ajax({
            url: '{{ url_for("test_room.edit_ajax") }}',
            type: 'POST',
            contentType: false,
            processData: false,
            data: formdata,
            success: function(response) {
                console.log("Edit ajax 통신 성공!" + response);
            },
            error: function(request, status, error) {
                console.log("Edit ajax 통신 실패!");
                console.log(status);
                console.log(error);
            }
        });

        // 메뉴 페이지로 이동
        // alert("시험이 수정되었습니다!!");
        location.href = "{{ url_for('test_room.menu') }}";
    });

</script>

{% endblock %}

DDOKDDOK/templates/test_room/edit_list.html
{% extends 'base.html' %}
{% block content %}

<div class="card card__editList card__global2">
    <div class="card-body">
        <h3 class="card-title text-center pt-2"><strong>시험 수정</strong></h3>
        <p class="card-title text-center border-bottom pb-2">시험을 수정하거나 삭제할 수 있습니다.</p>
        <div class="card-text">
            <ul class="list-group item-info-group">
                {% for id, state, title, start, end in test_room_list %}
                    {% if state == "before" %}
                        <li class="list-group-item mt-2">
                            <span class="item-info row p-1">
                                <span class="item-info"><strong>시험 제목 : {{ title }}</strong></span>
                                <span class="item-info">시험 번호 : {{ id }}</span>
                                <span class="item-info">시험 시간 : {{ start }} ~ {{ end }}</span>
                            </span>
                            <a href="{{ url_for('test_room.edit', test_room_id=id) }}" class="btn btn-success m-1 float-right"><strong>수정</strong></a>
                            <a href="{{ url_for('test_room.delete', test_room_id=id) }}" class="btn btn-danger m-1 float-right"><strong>삭제</strong></a>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

{% endblock %}

DDOKDDOK/templates/test_room/make.html
{% extends 'base.html' %}
{% block content %}

<div class="area__make area__global">
    <h2 class="text-center pt-2"><strong>시험 생성</strong></h2>
    <h4 class="text-center border-bottom pb-3">시험 번호 : {{ test_room_id }}</h4>

    <div class="container container1 my-3 mx-4 float-left">
        <h3 class="text-center border-bottom py-2">시험 제목 입력</h3>
        <div class="form-group">
            <input type="text" class="form-control" name="title" id="title">
        </div>
        <h3 class="text-center border-bottom py-2 mt-2">시험 시간 설정</h3>
        <form>
            <div><input type="date" id="dateForm"></div>
            <div class="mt-2">
                <input type="time" id="starttimeForm">
                ~
                <input type="time" id="endtimeForm">
            </div>
        </form>
    </div>
        
    <div class="container container2 my-3 mx-4 float-left">
        <h3 class="text-center border-bottom py-2">차단 프로그램 선택</h3>
        <ul class="list-group">
            {% for program in program_list %}
                <li class="list-group-item mb-2">
                    <div class="form-checkbox ml-3">
                        <input class="form-check-input" type="checkbox" value="" id="checkbox-input{{ loop.index - 1 }}">
                        <label class="form-check-label" for="checkbox{{ loop.index - 1 }}" id="checkbox-label{{ loop.index - 1 }}">{{ program }}</label>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>
        
    <div class="container container3 my-3 mx-4 float-left">
        <h3 class="text-center border-bottom py-2">학생 등록</h3>
        <form enctype="multipart/form-data">
            <ul class="list-group mb-3">
                <li class="list-group-item">1. 학생 사진을 등록하십시오.</li>
                <li class="list-group-item">2. 파일 이름을 학번으로 설정하십시오.</li>
            </ul>
            <div class="custom-file">
                <input type="file" class="custom-file-input" id="input_images" name="images[]" multiple>
                <label class="custom-file-label" data-browse="Browse">예) 20170843.jpg</label>
            </div>
        </form>
        <h3 class="text-center border-bottom py-2 mt-4">등록한 학생 리스트</h3>
        <div id="image_list"></div>
    </div>
</div>

<button class="btn btn-success btn-lg" id="makeTestRoomBtn"><strong>시험 생성</strong></button>

<script>    
    // 현재 날짜로 설정
    let today = new Date().toISOString();
    let dateForm = document.getElementById('dateForm');
    dateForm.value = today.slice(0, 10);
    dateForm.min = today.slice(0, 10);

    // 시작 시간 변경 시 종료 시간 자동 변경 (+1시간)
    $('#starttimeForm').change(() => {
        startTime = $('#starttimeForm').val();
        h = Number(startTime.slice(0, 2)) + 1;
        if (h < 10) {
            h = '0' + h;
        }
        m = startTime.slice(3, 5);
        $('#endtimeForm').attr({'value': h + ':' + m});
    });
    
    // 학생 리스트에 추가
    let image_list = [];
    const input_images = document.getElementById("input_images");
    input_images.addEventListener("change", uploadImages, false);
    function uploadImages() {
        const images = this.files;
        let bufferLen = image_list.length;
        for (let i = 0; i < images.length; i++) {
            const image = images[i];
            image_list.push(image);
            let div1 = document.createElement("div");
            div1.className = "card mt-1 mb-1";
            div1.style.width = "100%";
            let div2 = document.createElement("div");
            div2.className = "row no-gutters";

            let img = document.createElement("img");
            img.src = URL.createObjectURL(image);
            img.style = "max-width:100px; max-height: 130px;";
            div2.appendChild(img);

            let div3 = document.createElement("div");
            div3.className = "card-body";

            let span = document.createElement("span");
            span.className = "card-text";
            span.style = "white-space: pre-line;";
            span.innerText = image.name;
            div3.appendChild(span);

            let button = document.createElement("button");
            button.className = "btn btn-primary float-right deleteImgBtn" + (i + bufferLen);
            button.innerText = "삭제";
            button.addEventListener("click", deleteImage);
            div3.appendChild(button);

            div2.appendChild(div3);
            div1.appendChild(div2);
            document.getElementById("image_list").appendChild(div1);
        }
    }

    // 학생 리스트에서 삭제
    function deleteImage() {
        let index = $(this).parent().parent().parent().index();
        image_list.splice(index,1);
        this.parentNode.parentNode.parentNode.parentNode.removeChild(this.parentNode.parentNode.parentNode);
    }

    // 시험 생성 버튼 클릭 시 서버로 데이터 전송
    $('#makeTestRoomBtn').click( function () { 

        // 차단 프로그램 리스트 받아오기 (CheckBox)
        let block_list_string = "";
        for (let i = 0; i < '{{ program_list|length }}'; i++) {
            text = $('#checkbox-label' + i).text();
            if($('#checkbox-input' + i).is(":checked") === true) {
                block_list_string += text + ";";
            }
        }

        // 전송 할 폼데이터 생성
        let formdata = new FormData();
        formdata.append('test_room_id', '{{ test_room_id }}');
        formdata.append('professor_id', '{{ g.user.id }}');
        formdata.append('title', $('#title').val());
        formdata.append('block_list', block_list_string);
        formdata.append('date', document.getElementById('dateForm').value);
        formdata.append('start_time', document.getElementById('starttimeForm').value);
        formdata.append('end_time', document.getElementById('endtimeForm').value);
        formdata.append('length', image_list.length);
        for (let i = 0; i < image_list.length; i++) {
            formdata.append(i, image_list[i]);
        }
         
        // ajax 전송
        $.ajax({
            url: '{{ url_for("test_room.make_ajax") }}',
            type: 'POST',
            contentType: false,
            processData: false,
            data: formdata,
            success: function(response) {
                console.log("Make ajax 통신 성공!" + response);
            },
            error: function(request, status, error) {
                console.log("Make ajax 통신 실패!", status, error);
            }
        });

        // 메뉴 페이지로 이동
        // alert("시험이 생성되었습니다!!");
        location.href="{{ url_for('test_room.menu') }}";
   });

</script>

{% endblock %}

DDOKDDOK/templates/test_room/menu.html
{% extends 'base.html' %}
{% block content %}

<div class="card card__menu card__global">
    <div class="card-body">
        <h3 class="card-title text-center border-bottom py-2"><strong>메뉴</strong></h3>
        <div class="card-text">
            <a href="{{ url_for('test_room.make') }}" class="btn btn-primary btn-lg btn-block mb-1">시험 생성</a>
            <a href="{{ url_for('test_room.edit_list') }}" class="btn btn-primary btn-lg btn-block mb-1">시험 수정</a>
            <a href="{{ url_for('test_room.watching_list') }}" class="btn btn-primary btn-lg btn-block">시험 입장</a>
        </div>
    </div>
</div>

{% endblock %}

DDOKDDOK/templates/test_room/watching_before.html
{% extends 'base.html' %}
{% block content %}

<div class="area__watchingBefore area__global">
    <h2 class="text-center pt-2"><strong>{{ title }}</strong><span class="btn btn-dark btn-sm ml-2 mb-1"><strong>시작전</strong></span></h2>
    <h4 class="text-center border-bottom pb-3">시험 번호 : {{ test_room_id }} / 시험 시간 : {{ start_date }} ~ {{ end_date }} / 학생 수 : {{ student_list|length }}</h4>

    <div class="screen-group">
        {% for student_id in student_list %}
            <button class="btn btn-primary p-1 mb-1" id="{{ student_id }}"style="width: 430px;">
                <!-- 스크린 공유 방식 변경하기!! -->
                <img src="/static/img/no_screen.png" width="100%"/>
                <h4 class="pt-3">{{ student_id }}</h4>
            </button>
        {% endfor %}
    </div>
</div>
<a href="{{ url_for('test_room.start', test_room_id=test_room_id) }}" class="btn btn-success btn-lg" id="startTestRoomBtn"><strong>시험 시작</strong></a>

{% endblock %}

DDOKDDOK/templates/test_room/watching_result.html
{% extends 'base.html' %}
{% block content %}

<div class="card card__watchingResult">
    <div class="card-body">
        <h3 class="card-title text-center pt-2"><strong>시험 결과</strong></h3>
        <p class="card-title text-center border-bottom pb-2">부정 행위 감지 횟수가 많은 순서로 정렬되어있습니다.</p>
        <div class="card-text">
            <ul class="list-group item-info-group">
                {% for student_id, count in result_list %}
                <li class="list-group-item mt-2">
                    {% if loop.index < 4 %}
                        <span><mark>학생 번호 : {{ student_id }} 감지 횟수 : {{ count }}</mark></span>
                        <a href="{{ url_for('test_room.watching_result_detail', test_room_id=test_room_id, student_id=student_id) }}" class="btn btn-primary m-1 float-right">더보기</a>
                    {% else %}
                        <span>학생 번호 : {{ student_id }} 감지 횟수 : {{ count }}</span>
                        <a href="{{ url_for('test_room.watching_result_detail', test_room_id=test_room_id, student_id=student_id) }}" class="btn btn-primary m-1 float-right">더보기</a>
                    {% endif %}
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

{% endblock %}